# Generated by Django 5.1.2 on 2024-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(default='', max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
