# Generated by Django 5.1.2 on 2024-10-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_transaction_id_wallet_wallet_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
