# Generated by Django 5.1.2 on 2024-10-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIDDocument',
            fields=[
                ('did', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public_key', models.TextField()),
                ('authentication', models.JSONField(default=list)),
                ('service_endpoints', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('proof', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='DIDDocumentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('service_endpoint', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DIDResolutionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolver', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DIDTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('REVOKE', 'Revoke')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField()),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
