# Generated by Django 5.1.2 on 2024-10-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('stake', models.DecimalField(decimal_places=8, max_digits=20)),
                ('public_key', models.TextField()),
                ('rewards', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('blocks_validated', models.IntegerField(default=0)),
                ('is_slashed', models.BooleanField(default=False)),
                ('validation_failures', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
