# Generated by Django 5.1.2 on 2024-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='validator',
            name='last_block_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validator',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='validator',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
