# Generated by Django 5.1.2 on 2024-10-25 12:59

import apps.blockchain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_validator_is_active_validator_last_block_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diddocument',
            name='authentication',
            field=models.JSONField(default=apps.blockchain.models.default_empty_list),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='metadata',
            field=models.JSONField(default=apps.blockchain.models.default_empty_dict),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='service_endpoints',
            field=models.JSONField(default=apps.blockchain.models.default_empty_list),
        ),
        migrations.DeleteModel(
            name='DIDDocumentService',
        ),
    ]
