# Generated by Django 5.1.2 on 2024-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_alter_diddocument_authentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='private_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
