# Generated by Django 5.1.2 on 2024-10-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_validator_private_key_pem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diddocument',
            name='authentication',
        ),
        migrations.AddField(
            model_name='diddocument',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
