# Generated by Django 5.1.2 on 2024-10-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_remove_diddocument_authentication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validator',
            old_name='private_key_pem',
            new_name='private_key',
        ),
        migrations.RemoveField(
            model_name='diddocument',
            name='private_key',
        ),
    ]
