# Generated by Django 5.1.2 on 2024-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=142),
        ),
    ]
