# Generated by Django 5.1.2 on 2024-10-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='did',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
